#include "dmn/detail/ods.hpp"

#include <domino/global.h>
#include <domino/ods.h>

#include <utility>

#include "dmn/detail/runtime.hpp"

namespace ods = dmn::detail::ods;
using ods::type;

static_assert(std::to_underlying(type::timedate) == _TIMEDATE);
static_assert(std::to_underlying(type::timedate_pair) == _TIMEDATE_PAIR);
static_assert(std::to_underlying(type::aligned_number_pair) == _ALIGNED_NUMBER_PAIR);
static_assert(std::to_underlying(type::list) == _LIST);
static_assert(std::to_underlying(type::range) == _RANGE);
static_assert(std::to_underlying(type::dbid) == _DBID);
static_assert(std::to_underlying(type::item) == _ITEM);
static_assert(std::to_underlying(type::item_table) == _ITEM_TABLE);
static_assert(std::to_underlying(type::search_match) == _SEARCH_MATCH);
static_assert(std::to_underlying(type::originatorid) == _ORIGINATORID);
static_assert(std::to_underlying(type::object_descriptor) == _OBJECT_DESCRIPTOR);
static_assert(std::to_underlying(type::universalnoteid) == _UNIVERSALNOTEID);
static_assert(std::to_underlying(type::view_table_format) == _VIEW_TABLE_FORMAT);
static_assert(std::to_underlying(type::view_column_format) == _VIEW_COLUMN_FORMAT);
static_assert(std::to_underlying(type::notelink) == _NOTELINK);
static_assert(std::to_underlying(type::licenseid) == _LICENSEID);
static_assert(std::to_underlying(type::view_format_header) == _VIEW_FORMAT_HEADER);
static_assert(std::to_underlying(type::view_table_format2) == _VIEW_TABLE_FORMAT2);
static_assert(std::to_underlying(type::dbreplicainfo) == _DBREPLICAINFO);
static_assert(std::to_underlying(type::fileobject) == _FILEOBJECT);
static_assert(std::to_underlying(type::collation) == _COLLATION);
static_assert(std::to_underlying(type::collate_descriptor) == _COLLATE_DESCRIPTOR);
static_assert(std::to_underlying(type::cdkeyword) == _CDKEYWORD);
static_assert(std::to_underlying(type::cdlink2) == _CDLINK2);
static_assert(std::to_underlying(type::cdlinkexport2) == _CDLINKEXPORT2);
static_assert(std::to_underlying(type::cdparagraph) == _CDPARAGRAPH);
static_assert(std::to_underlying(type::cdpabdefinition) == _CDPABDEFINITION);
static_assert(std::to_underlying(type::cdpabreference) == _CDPABREFERENCE);
static_assert(std::to_underlying(type::cdfield_pre_36) == _CDFIELD_PRE_36);
static_assert(std::to_underlying(type::cdtext) == _CDTEXT);
static_assert(std::to_underlying(type::cddocument) == _CDDOCUMENT);
static_assert(std::to_underlying(type::cdmetafile) == _CDMETAFILE);
static_assert(std::to_underlying(type::cdbitmap) == _CDBITMAP);
static_assert(std::to_underlying(type::cdheader) == _CDHEADER);
static_assert(std::to_underlying(type::cdfield) == _CDFIELD);
static_assert(std::to_underlying(type::cdfonttable) == _CDFONTTABLE);
static_assert(std::to_underlying(type::cdface) == _CDFACE);
static_assert(std::to_underlying(type::cdcgm) == _CDCGM);
static_assert(std::to_underlying(type::cdtiff) == _CDTIFF);
static_assert(std::to_underlying(type::cdbitmapheader) == _CDBITMAPHEADER);
static_assert(std::to_underlying(type::cdbitmapsegment) == _CDBITMAPSEGMENT);
static_assert(std::to_underlying(type::cdcolortable) == _CDCOLORTABLE);
static_assert(std::to_underlying(type::cdpatterntable) == _CDPATTERNTABLE);
static_assert(std::to_underlying(type::cdgraphic) == _CDGRAPHIC);
static_assert(std::to_underlying(type::cdpmmetaheader) == _CDPMMETAHEADER);
static_assert(std::to_underlying(type::cdwinmetaheader) == _CDWINMETAHEADER);
static_assert(std::to_underlying(type::cdmacmetaheader) == _CDMACMETAHEADER);
static_assert(std::to_underlying(type::cdcgmmeta) == _CDCGMMETA);
static_assert(std::to_underlying(type::cdpmmetaseg) == _CDPMMETASEG);
static_assert(std::to_underlying(type::cdwinmetaseg) == _CDWINMETASEG);
static_assert(std::to_underlying(type::cdmacmetaseg) == _CDMACMETASEG);
static_assert(std::to_underlying(type::cdddebegin) == _CDDDEBEGIN);
static_assert(std::to_underlying(type::cdddeend) == _CDDDEEND);
static_assert(std::to_underlying(type::cdtablebegin) == _CDTABLEBEGIN);
static_assert(std::to_underlying(type::cdtablecell) == _CDTABLECELL);
static_assert(std::to_underlying(type::cdtableend) == _CDTABLEEND);
static_assert(std::to_underlying(type::cdstylename) == _CDSTYLENAME);
static_assert(std::to_underlying(type::fileobject_macext) == _FILEOBJECT_MACEXT);
static_assert(std::to_underlying(type::fileobject_hpfsext) == _FILEOBJECT_HPFSEXT);
static_assert(std::to_underlying(type::cdolebegin) == _CDOLEBEGIN);
static_assert(std::to_underlying(type::cdoleend) == _CDOLEEND);
static_assert(std::to_underlying(type::cdhotspotbegin) == _CDHOTSPOTBEGIN);
static_assert(std::to_underlying(type::cdhotspotend) == _CDHOTSPOTEND);
static_assert(std::to_underlying(type::cdbutton) == _CDBUTTON);
static_assert(std::to_underlying(type::cdbar) == _CDBAR);
static_assert(std::to_underlying(type::cdqueryheader) == _CDQUERYHEADER);
static_assert(std::to_underlying(type::cdquerytextterm) == _CDQUERYTEXTTERM);
static_assert(std::to_underlying(type::cdactionheader) == _CDACTIONHEADER);
static_assert(std::to_underlying(type::cdactionmodifyfield) == _CDACTIONMODIFYFIELD);
static_assert(std::to_underlying(type::ods_assiststruct) == _ODS_ASSISTSTRUCT);
static_assert(std::to_underlying(type::viewmap_header_record) == _VIEWMAP_HEADER_RECORD);
static_assert(std::to_underlying(type::viewmap_rect_record) == _VIEWMAP_RECT_RECORD);
static_assert(std::to_underlying(type::viewmap_bitmap_record) == _VIEWMAP_BITMAP_RECORD);
static_assert(std::to_underlying(type::viewmap_region_record) == _VIEWMAP_REGION_RECORD);
static_assert(
  std::to_underlying(type::viewmap_polygon_record_byte) == _VIEWMAP_POLYGON_RECORD_BYTE
);
static_assert(
  std::to_underlying(type::viewmap_polyline_record_byte) == _VIEWMAP_POLYLINE_RECORD_BYTE
);
static_assert(std::to_underlying(type::viewmap_action_record) == _VIEWMAP_ACTION_RECORD);
static_assert(std::to_underlying(type::ods_assistruninfo) == _ODS_ASSISTRUNINFO);
static_assert(std::to_underlying(type::cdactionreply) == _CDACTIONREPLY);
static_assert(std::to_underlying(type::cdactionformula) == _CDACTIONFORMULA);
static_assert(std::to_underlying(type::cdactionlotusscript) == _CDACTIONLOTUSSCRIPT);
static_assert(std::to_underlying(type::cdquerybyfield) == _CDQUERYBYFIELD);
static_assert(std::to_underlying(type::cdactionsendmail) == _CDACTIONSENDMAIL);
static_assert(std::to_underlying(type::cdactiondbcopy) == _CDACTIONDBCOPY);
static_assert(std::to_underlying(type::cdactiondelete) == _CDACTIONDELETE);
static_assert(std::to_underlying(type::cdactionbyform) == _CDACTIONBYFORM);
static_assert(std::to_underlying(type::ods_assistfieldstruct) == _ODS_ASSISTFIELDSTRUCT);
static_assert(std::to_underlying(type::cdaction) == _CDACTION);
static_assert(std::to_underlying(type::cdactionreadmarks) == _CDACTIONREADMARKS);
static_assert(std::to_underlying(type::cdextfield) == _CDEXTFIELD);
static_assert(std::to_underlying(type::cdlayout) == _CDLAYOUT);
static_assert(std::to_underlying(type::cdlayouttext) == _CDLAYOUTTEXT);
static_assert(std::to_underlying(type::cdlayoutend) == _CDLAYOUTEND);
static_assert(std::to_underlying(type::cdlayoutfield) == _CDLAYOUTFIELD);
static_assert(std::to_underlying(type::viewmap_dataset_record) == _VIEWMAP_DATASET_RECORD);
static_assert(std::to_underlying(type::cddocautolaunch) == _CDDOCAUTOLAUNCH);
static_assert(std::to_underlying(type::cdpabhide) == _CDPABHIDE);
static_assert(std::to_underlying(type::cdpabformularef) == _CDPABFORMULAREF);
static_assert(std::to_underlying(type::cdactionbar) == _CDACTIONBAR);
static_assert(std::to_underlying(type::cdactionfolder) == _CDACTIONFOLDER);
static_assert(std::to_underlying(type::cdactionnewsletter) == _CDACTIONNEWSLETTER);
static_assert(std::to_underlying(type::cdactionrunagent) == _CDACTIONRUNAGENT);
static_assert(std::to_underlying(type::cdactionsenddocument) == _CDACTIONSENDDOCUMENT);
static_assert(std::to_underlying(type::cdqueryformula) == _CDQUERYFORMULA);
static_assert(std::to_underlying(type::cdquerybyform) == _CDQUERYBYFORM);
static_assert(std::to_underlying(type::ods_assistrunobjectheader) == _ODS_ASSISTRUNOBJECTHEADER);
static_assert(std::to_underlying(type::ods_assistrunobjectentry) == _ODS_ASSISTRUNOBJECTENTRY);
static_assert(std::to_underlying(type::cdoleobj_info) == _CDOLEOBJ_INFO);
static_assert(std::to_underlying(type::cdlayoutgraphic) == _CDLAYOUTGRAPHIC);
static_assert(std::to_underlying(type::cdquerybyfolder) == _CDQUERYBYFOLDER);
static_assert(std::to_underlying(type::cdqueryusesform) == _CDQUERYUSESFORM);
static_assert(std::to_underlying(type::view_column_format2) == _VIEW_COLUMN_FORMAT2);
static_assert(std::to_underlying(type::viewmap_text_record) == _VIEWMAP_TEXT_RECORD);
static_assert(std::to_underlying(type::cdlayoutbutton) == _CDLAYOUTBUTTON);
static_assert(std::to_underlying(type::cdquerytopic) == _CDQUERYTOPIC);
static_assert(std::to_underlying(type::cdlsobject) == _CDLSOBJECT);
static_assert(std::to_underlying(type::cdhtmlheader) == _CDHTMLHEADER);
static_assert(std::to_underlying(type::cdhtmlsegment) == _CDHTMLSEGMENT);
static_assert(std::to_underlying(type::sched_list) == _SCHED_LIST);
static_assert(std::to_underlying(type::sched_entry) == _SCHED_ENTRY);
static_assert(std::to_underlying(type::schedule) == _SCHEDULE);
static_assert(std::to_underlying(type::cdtexteffect) == _CDTEXTEFFECT);
static_assert(std::to_underlying(type::view_calendar_format) == _VIEW_CALENDAR_FORMAT);
static_assert(std::to_underlying(type::cdstoragelink) == _CDSTORAGELINK);
static_assert(std::to_underlying(type::activeobject) == _ACTIVEOBJECT);
static_assert(std::to_underlying(type::activeobjectparam) == _ACTIVEOBJECTPARAM);
static_assert(std::to_underlying(type::activeobjectstoragelink) == _ACTIVEOBJECTSTORAGELINK);
static_assert(std::to_underlying(type::cdtransparenttable) == _CDTRANSPARENTTABLE);
static_assert(std::to_underlying(type::viewmap_polygon_record) == _VIEWMAP_POLYGON_RECORD);
static_assert(std::to_underlying(type::viewmap_polyline_record) == _VIEWMAP_POLYLINE_RECORD);
static_assert(std::to_underlying(type::sched_detail_list) == _SCHED_DETAIL_LIST);
static_assert(std::to_underlying(type::cdalternatebegin) == _CDALTERNATEBEGIN);
static_assert(std::to_underlying(type::cdalternateend) == _CDALTERNATEEND);
static_assert(std::to_underlying(type::cdolertmarker) == _CDOLERTMARKER);
static_assert(std::to_underlying(type::hsolerichtext) == _HSOLERICHTEXT);
static_assert(std::to_underlying(type::cdanchor) == _CDANCHOR);
static_assert(std::to_underlying(type::cdhrule) == _CDHRULE);
static_assert(std::to_underlying(type::cdalttext) == _CDALTTEXT);
static_assert(std::to_underlying(type::cdactionjavaagent) == _CDACTIONJAVAAGENT);
static_assert(std::to_underlying(type::cdhtmlbegin) == _CDHTMLBEGIN);
static_assert(std::to_underlying(type::cdhtmlend) == _CDHTMLEND);
static_assert(std::to_underlying(type::cdhtmlformula) == _CDHTMLFORMULA);
static_assert(std::to_underlying(type::cdbeginrecord) == _CDBEGINRECORD);
static_assert(std::to_underlying(type::cdendrecord) == _CDENDRECORD);
static_assert(std::to_underlying(type::cdverticalalign) == _CDVERTICALALIGN);
static_assert(std::to_underlying(type::cdfloat) == _CDFLOAT);
static_assert(std::to_underlying(type::cdtimerinfo) == _CDTIMERINFO);
static_assert(std::to_underlying(type::cdtablerowheight) == _CDTABLEROWHEIGHT);
static_assert(std::to_underlying(type::cdtablelabel) == _CDTABLELABEL);
static_assert(std::to_underlying(type::cdtransition) == _CDTRANSITION);
static_assert(std::to_underlying(type::cdplaceholder) == _CDPLACEHOLDER);
static_assert(std::to_underlying(type::cdembeddedview) == _CDEMBEDDEDVIEW);
static_assert(std::to_underlying(type::cdembeddedoutline) == _CDEMBEDDEDOUTLINE);
static_assert(std::to_underlying(type::cdregionbegin) == _CDREGIONBEGIN);
static_assert(std::to_underlying(type::cdregionend) == _CDREGIONEND);
static_assert(std::to_underlying(type::cdcellbackgrounddata) == _CDCELLBACKGROUNDDATA);
static_assert(std::to_underlying(type::framesetlength) == _FRAMESETLENGTH);
static_assert(std::to_underlying(type::cdframesetheader) == _CDFRAMESETHEADER);
static_assert(std::to_underlying(type::cdframeset) == _CDFRAMESET);
static_assert(std::to_underlying(type::cdframe) == _CDFRAME);
static_assert(std::to_underlying(type::cdtarget) == _CDTARGET);
static_assert(std::to_underlying(type::cdresource) == _CDRESOURCE);
static_assert(std::to_underlying(type::cdmapelement) == _CDMAPELEMENT);
static_assert(std::to_underlying(type::cdareaelement) == _CDAREAELEMENT);
static_assert(std::to_underlying(type::cdrect) == _CDRECT);
static_assert(std::to_underlying(type::cdpoint) == _CDPOINT);
static_assert(std::to_underlying(type::cdembeddedctl) == _CDEMBEDDEDCTL);
static_assert(std::to_underlying(type::cdevent) == _CDEVENT);
static_assert(std::to_underlying(type::mime_part) == _MIME_PART);
static_assert(std::to_underlying(type::cdpretablebegin) == _CDPRETABLEBEGIN);
static_assert(std::to_underlying(type::cdcolor) == _CDCOLOR);
static_assert(std::to_underlying(type::cdborderinfo) == _CDBORDERINFO);
static_assert(std::to_underlying(type::cdext2field) == _CDEXT2FIELD);
static_assert(std::to_underlying(type::cdembeddedschedctl) == _CDEMBEDDEDSCHEDCTL);
static_assert(std::to_underlying(type::rfc822itemdesc) == _RFC822ITEMDESC);
static_assert(std::to_underlying(type::color_value) == _COLOR_VALUE);
static_assert(std::to_underlying(type::cdblobpart) == _CDBLOBPART);
static_assert(std::to_underlying(type::cdimageheader) == _CDIMAGEHEADER);
static_assert(std::to_underlying(type::cdimagesegment) == _CDIMAGESEGMENT);
static_assert(std::to_underlying(type::view_table_format3) == _VIEW_TABLE_FORMAT3);
static_assert(std::to_underlying(type::cdidname) == _CDIDNAME);
static_assert(std::to_underlying(type::cdactionbarext) == _CDACTIONBAREXT);
static_assert(std::to_underlying(type::cdlinkcolors) == _CDLINKCOLORS);
static_assert(std::to_underlying(type::cdcaption) == _CDCAPTION);
static_assert(std::to_underlying(type::cdfieldhint) == _CDFIELDHINT);
static_assert(std::to_underlying(type::cdlsobject_r6) == _CDLSOBJECT_R6);
static_assert(std::to_underlying(type::cdinline) == _CDINLINE);
static_assert(std::to_underlying(type::cdtextpropertiestable) == _CDTEXTPROPERTIESTABLE);
static_assert(std::to_underlying(type::cdspanrecord) == _CDSPANRECORD);
static_assert(std::to_underlying(type::cddecsfield) == _CDDECSFIELD);
static_assert(std::to_underlying(type::view_table_format4) == _VIEW_TABLE_FORMAT4);
static_assert(std::to_underlying(type::cdlayer) == _CDLAYER);
static_assert(std::to_underlying(type::cdpositioning) == _CDPOSITIONING);
static_assert(std::to_underlying(type::cdboxsize) == _CDBOXSIZE);
static_assert(std::to_underlying(type::cdembeddededitctl) == _CDEMBEDDEDEDITCTL);
static_assert(std::to_underlying(type::cdembeddedschedctlextra) == _CDEMBEDDEDSCHEDCTLEXTRA);
static_assert(std::to_underlying(type::log_searchr6_req) == _LOG_SEARCHR6_REQ);
static_assert(std::to_underlying(type::cdbackgroundproperties) == _CDBACKGROUNDPROPERTIES);
static_assert(std::to_underlying(type::view_column_format3) == _VIEW_COLUMN_FORMAT3);
static_assert(std::to_underlying(type::view_column_format4) == _VIEW_COLUMN_FORMAT4);
static_assert(std::to_underlying(type::cdtextproperty) == _CDTEXTPROPERTY);
static_assert(std::to_underlying(type::cddataflags) == _CDDATAFLAGS);
static_assert(std::to_underlying(type::cdfileheader) == _CDFILEHEADER);
static_assert(std::to_underlying(type::cdfilesegment) == _CDFILESEGMENT);
static_assert(std::to_underlying(type::cdevententry) == _CDEVENTENTRY);
static_assert(std::to_underlying(type::cdactionext) == _CDACTIONEXT);
static_assert(std::to_underlying(type::cdembeddedcalctl) == _CDEMBEDDEDCALCTL);
static_assert(std::to_underlying(type::cdtabledataextension) == _CDTABLEDATAEXTENSION);
static_assert(std::to_underlying(type::cdlargeparagraph) == _CDLARGEPARAGRAPH);
static_assert(std::to_underlying(type::cdignore) == _CDIGNORE);
static_assert(std::to_underlying(type::view_column_format5) == _VIEW_COLUMN_FORMAT5);
static_assert(std::to_underlying(type::cdembedextrainfo) == _CDEMBEDEXTRAINFO);
static_assert(std::to_underlying(type::cdembeddedcontactlist) == _CDEMBEDDEDCONTACTLIST);
static_assert(std::to_underlying(type::view_column_format6) == _VIEW_COLUMN_FORMAT6);
static_assert(std::to_underlying(type::note_seal2_hdr) == _NOTE_SEAL2_HDR);
static_assert(std::to_underlying(type::note_seal2) == _NOTE_SEAL2);
static_assert(std::to_underlying(type::note_record_desc) == _NOTE_RECORD_DESC);

auto ods::size(type typ) -> uint16_t {
  dmn::detail::session::instance();
  return ODSLength(std::to_underlying(typ));
}

void ods::write(void* dst, const void* src, type typ) {
  dmn::detail::session::instance();
  ODSWriteMemory(static_cast<void*>(&dst), std::to_underlying(typ), src, 1);
}

void ods::read(void* dst, const void* src, type typ) {
  dmn::detail::session::instance();
  ODSReadMemory(static_cast<void*>(&src), std::to_underlying(typ), dst, 1);
}
